name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: LogoDetect.sln
      Project_Path: LogoDetect/LogoDetect.csproj

    steps:
    - name: Extract Version
      id: extract_version
      shell: bash
      run: |
        VERSION=$(echo "${GITHUB_REF_NAME}" | cut -c2-)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v3  
      with:
        fetch-depth: 0

    - name: Setup .NET    
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies    
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build  
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Publish  
      run: dotnet publish ${{ env.Project_Path }} --self-contained -r win-x64 -o LogoDetect/publish

    - name: Install Velopack CLI  
      run: dotnet tool install --global vpk
  
    - name: Create Velopack Release
      run: |
        vpk pack --packId "natevoci.LogoDetect" --packVersion "${{ steps.extract_version.outputs.version }}" --packDir "LogoDetect/publish" --mainExe "LogoDetect.exe"

    - name: Log Releases Directory Listing
      run: |
        echo "Contents of LogoDetect/Releases:"
        dir /b /s LogoDetect

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false
        files: |
          Releases/*
          Releases/natevoci.LogoDetect-win-Setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
